//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34011
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModul.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDb)\\v11.0;AttachDbFilename=D:\\Softbucks\\Softbucks\\App_Data\\aspn" +
            "et-Softbucks-20140302121355.mdf;Initial Catalog=aspnet-Softbucks-20140302121355;" +
            "Integrated Security=True")]
        public string aspnet_Softbucks_20140302121355ConnectionString {
            get {
                return ((string)(this["aspnet_Softbucks_20140302121355ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDb)\\v11.0;AttachDbFilename=D:\\Cloud@Mail.Ru\\Softbucks\\Softbucks" +
            "\\App_Data\\aspnet-Softbucks-20140302121355.mdf;Initial Catalog=aspnet-Softbucks-2" +
            "0140302121355;Integrated Security=True")]
        public string aspnet_Softbucks_20140302121355ConnectionString1 {
            get {
                return ((string)(this["aspnet_Softbucks_20140302121355ConnectionString1"]));
            }
        }
    }
}
